version: '3.1'

services:

  db:
    image: postgres:10.1
    environment:
      POSTGRES_PASSWORD: Passw0rd
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    build: ./my_project
    command: python my_project/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code    # mounts . in host to /code in container
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db

volumes:
  pgdata:

networks:
  backend: